language: java
jdk:
  - openjdk11

services:
  - docker

install: true

script:
  - docker build -t insurance-portal/member-details .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master